### ISSUE TITLE
Merges to master always cause commitsar to fail

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-threads#153]
This is because there's only one commit, and its being filtered out. Here's the CI output:

```
Starting analysis of commits on branch HEAD

1 commits filtered out

Found 0 commit to check
No commits found, please check you are on a branch outside of main
```

**Comment by fallion** [comment]
HI @carsonfarmer 
Can I help with this?

**Comment by carsonfarmer** [comment]
Certainly!

**Comment by fallion** [comment]
I'm redoing the internals today, but I hope to ship a fix for this tomorrow in a new version. I'll make it so that if there is only a filtered commit it won't fail, since this is how it works in the merge commit flow.

Question is: How far back do you want it to check if it is on master? Would you like to be able to configure this? 

Thanks for the help :)

**Comment by carsonfarmer** [comment]
Ah thanks @fallion, and apologies for the delayed response. I don't _think_ from our perspective we need to go all that far back to check, and we're unlikely to need to configure this at this time.

P.S. Thanks for building/releasing such a handy tool!

**Comment by asutula** [comment]
FWIW, I had the same error in anohter repo, and the error actually says to be sure you're not running commitsar on the main branch (`master` in our case). So simply just disabled it for running on commits to master.
