### ISSUE TITLE
Error: Thread id mismatch when trying to use `db.open`

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#191]
Trying to following the instructions in https://docs.textile.io/threads/introduction/#developer-api

If I do the following,

```
    const threadID: ThreadID = ThreadID.fromRandom()
    const db = new Database()
    await db.open({ threadID })
```

I get the error, `Error: Thread id mismatch`

**Comment by carsonfarmer** [comment]
This is actually the intended (though obviously unintuitive) behavior. Essentially here, because there (is likely) already an existing db under the default name `threads.db`, when you are calling `db.open`, it is attempting to restore the existing database, but since you are specifying a _new_ thread id for an _existing_ it fails. Not a great DX, so let's fix this.

Here are the possible scenarios we'd need to be able to handle (some of which, I think we already handle correctly):

* Brand new DB, brand new ThreadID
  * Create new db, specify new ThreadID, return, all good
* Existing DB, no ThreadID
  * Open existing db, use default ThreadID, return, all good
* Existing DB, existing ThreadID
  * Open existing db, use correct ThreadID, return, all good
* Existing DB, brand new ThreaID
  * Right now, we fail here because they won't match/aren't compatible

* Possible different options:
  * Fail, but use a better error message
  * Wipe existing DB and start a new one (seems dangerous), possibly warning about this
  * Create new secondary DB and use that, possibly warning about this
 
Totally different approach: scope all DBs by their ThreadID (or even just a random ID, or have 'name' be a required constructor parameter), so you'll always get a new one if you specify a new ThreadID. Right now, the default is to just use a db called `threads.db`, we could make it so that calling open or init returns the new DB name, and then it is up to developers to store this off and remember it for their app? Having a deterministic name is useful because any app knows where to look (and will be scoped to their domain in a browser anyway). Or, we could even have different behaviours in node and browser.

I think my preference is to just require the caller to specify a name for the db, and scope the file to that name. This works the same in browser and node, isn't a heavy burden on the developer, and is a quick fix that requires minimal retooling. Scoping by TheadID seems ok, but maybe not as forward compatible if we start to support multi-thread dbs?

Your thoughts @andrewxhill ?

**Comment by andrewxhill** [comment]
Well... maybe easier to start.

- I am a new user so haven't figured out what errors i need to escape and how to parse them if i do see them.
- so, `Error: Thread id mismatch` isn't a very good error to help me keep building. 

Maybe we could detect this and provide better error or help? If I had been able to tell what was going on from the error, I would have just tossed it in a try/catch and if it was already open just continued

**Comment by carsonfarmer** [comment]
Cool, that's option one above, but I feel like we can do better maybe? But at the very least, we can 
* Detect if existing db and non-matching ThreadID
  * `throw new Error("Input ThreadID does not match DB Thread ID. Consider creating new DB or use matching ThreadID. Leave ThreadID blank to use default.")`
* Require that a developer inputs either a new Datastore instance, _or_ a string name. That way, they must explicitly specify _where_ things are being saved.
