### ISSUE TITLE
Multistep version of getToken

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#208]
Right now, getToken handles a bunch of things for the developer so it's simple. Pass in an identity and get back a token. However, if a developer wants to sandbox their users from the APIs a bit more, they may not want to pass a full private key into whatever process is handling this for their user. 

Instead, a flow like the following would be useful:

`getToken(publicKey)` returns a message that needs to be signed and sent back in the next step.

thinking @carsonfarmer has thought about this a bit already.

**Comment by carsonfarmer** [comment]
This is actually exactly what getToken wraps up. See here https://github.com/textileio/js-threads/blob/master/packages/network-client/src/index.ts#L129. The private key is actually never included in any calls to external functions or processes. However, this flow could be uncoupled if we wanted.

Having said that, the way it is now, the actual _key_ doesn’t need to be shared, just an interface that can sign. So the developer or user can actually already do the above flow where the signing can happen “separately” from the internals of getToken. The only thing that happens in getToken is some data is passed to the provided interface for signing and that gets sent back to the service along with the public key. Right now, our default “key” is used to satisfy this interface, but that need not be the case.

**Comment by carsonfarmer** [comment]
One proposal for an alternative flow, if we felt one was needed, could be to support a callback for getToken, which would essentially take the challenge that the service sends, and then return the signed response. This might be a slightly more decoupled flow while still keeping things pretty simple for the developer/user? Yes, I quite like that actually. What do toy think @andrewxhill? Maybe even making _thst_ the default flow, just because it does feel slightly ‘safer’ than passing the interface?

**Comment by andrewxhill** [comment]
yes, that's perfect. def leave what you've already got as an easy option. but if you had that i could whip up a pretty nice demo where the user key doesn't have to leave their control
